Apple home page
gango-anan/apple-clone pull request #1
Opened 2020-10-14 22:37 UTC by gango-anan

## In this Project I :
- I created index.html file to house the web page structure and the main.css file to contain the general styling rules of the page
- Added empty html elements to the index.html file to form the structure of the page
- Styled the navigation bar to mimic the original page navigation bar
- Styled the main section area which contains the main content of the page
- Finally Styled the footer of the page
- Wrote the project README file to help guide the intended users of the project how to generally get started with the page

2020-10-15 00:10 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @gango-anan  . Thanks for submitting you project!

Great thing this project has and has done well:
:100: Use of semantic HTML
:100: Great Acknowledgment! Love it! 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] LinkedIn link is broken in README

- [ ] There is no "aside" element in the website, the elements wrapped inside the tag would be better positioned inside the main section.

- [ ] The clone is not displaying the 4 image elements
![image](https://user-images.githubusercontent.com/25774518/96058027-ec9f4c00-0e4f-11eb-9021-a69792dbebc7.png)

- [ ] The image is not displaying correctly. These elements shouldn't appear. 
![image](https://user-images.githubusercontent.com/25774518/96058097-10629200-0e50-11eb-9718-ba914945eaa1.png)

- [ ] Navbar hover effect has no rounded corners for that match the normal one.
![image](https://user-images.githubusercontent.com/25774518/96058381-a3033100-0e50-11eb-841a-e3c712167b94.png)
![image](https://user-images.githubusercontent.com/25774518/96058395-af878980-0e50-11eb-899d-aea73ec9f7ab.png)

### [OPTIONAL]  :yellow_circle:  

- [ ] I would suggest to leave out the XAMPP config and put it as a pre-requisite. This way you can focus on the steps that are required for the website to display locally. And mention only in the "how to run" section a step like: start server and run in localhost.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-15 22:43 UTC, gango-anan commented
Thanks for the observations made, they were invaluable; all recommended changes have be done, waiting for the next verdict, thanks.

2020-10-15 23:08 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] the first line of the footer, should have one section on the right and the other on the left, yours is all on the left

| Yours | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11758151/96195019-97dcfd80-0f43-11eb-8c00-11f0f773f2e1.png) | ![image](https://user-images.githubusercontent.com/11758151/96195037-a1666580-0f43-11eb-8034-92095c4af24b.png) |

- [ ] check more below 👇 



### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-10-15 23:08 UTC, Spayco commented on index.html
> +  </main>
- [ ] these should be links (to other articles or `#`) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))

2020-10-15 23:37 UTC, gango-anan commented
Fixed all the issues raised, awaiting approval, thanks.

2020-10-15 23:38 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-10-16 00:04 UTC, gango-anan commented
Project Approved, merging apple-home-page branch to the master branch

2020-10-16 00:07 UTC, merged